version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    docker:
      - image: circleci/node:13.8.0
    # Add steps to the job
    steps:
      - chekout
      - run: npm i
      - save_cache:
        key: "npm_packages"
        path:
          - /src/node_modules
      - run: npm run lint

  test:
    docker:
      -image: circleci/node:13.8.0

    steps:
      - checkout
      - restore_cache:
        keys: 
          - "npm_packages"

      - run: npm i
      - run: npm run test

  analyse:
    docker:
      -image: circleci/node:13.8.0

    steps:
      - checkout
      - restore_cache:
        keys:
          - "npm_packages"
      - run: npm audit


# Invoke jobs via workflows
workflows:
  my_workflow:
    jobs:
      - build
      - test
          requires:
            - build
      - analyse
          requires:
            - test